openapi: "3.0.0"
info:
  version: "0.1.0"
  title: whatsup
paths:
  /user:
    get:
      summary: get user profile
      operationId: getUser
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    post:
      summary: register a user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /user/login:
    post:
      summary: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
  /user/logout:
    post:
      summary: logout

  /chats:
    get:
      summary: get all chats
      operationId: listChats
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chats"
    post:
      summary: create a chat
      operationId: createChat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chat"
  /chats/{id}
    get:
      summary: get a chat
      operationId: getChat
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          content:
            application/json
              schema:
                $ref: "#/components/schemas/Chat"
    delete:
      summary: delete a char
      operationId: deleteChat
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
      required:
        - id
        - username
        - password
    Chat:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
